### ISSUE TITLE
Live streaming

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2734]
Hi, 

I capture audio and video from a canvas on my site and wondered if it possible to live stream this using a simple like.  So If i draw on a canvas as say something then the streamer plays this to its audience?

**Comment by DanielnetoDotCom** [comment]
If you can transform it into an RTMP publisher it is possible.

**Comment by aliasgarvanak** [comment]
live stream is not working whenever I am trying to access it. It is not working in my local repo nor your demo url

**Comment by DanielnetoDotCom** [comment]
thanks for notice the demo site issue

On the demo site, the problem was an expired SSL

![image](https://user-images.githubusercontent.com/18009293/77317324-c2d2dc00-6ce9-11ea-93d4-6f6bdc1fd997.png)

it is fixed now

![image](https://user-images.githubusercontent.com/18009293/77318915-aab08c00-6cec-11ea-9335-6e456c59685f.png)

**Comment by aliasgarvanak** [comment]
Hello,

It is still showing me the error in the demo site. Live feature is not
working. Giving me the error media could not be loaded.

**Comment by DanielnetoDotCom** [comment]
it may be something on your side.

here is working pretty fine.

**Comment by aliasgarvanak** [comment]
I have tested with all the browsers and mobile devices too. Can you please
send me any live link to see?

**Comment by aliasgarvanak** [comment]
Please find attached.

**Comment by DanielnetoDotCom** [comment]
There is no attachment.

but you can see the live working here https://demo.avideo.com/plugin/Live/?c=HillsongUNITED

**Comment by aliasgarvanak** [comment]
I have checked the link you sent and it is working fine. But why my link is
not working for a live and showing the error in my local system and live
system too in your demo url ?

Thanks & Regards,
AliAsgar S. Vanak
Mo : +917383862385

**Comment by aliasgarvanak** [comment]
I am just wondering if I am making something wrong while making live ?
Please let me know. Because in local and demo url, everytime I try to go
live, same error I faced.
Thanks & Regards,
AliAsgar S. Vanak
Mo : +917383862385

**Comment by aliasgarvanak** [comment]
Expecting your response.

Thanks & Regards,
AliAsgar S. Vanak
Mo : +917383862385

**Comment by DanielnetoDotCom** [comment]
Check your streamer log file and your nginx log file.

**Comment by aliasgarvanak** [comment]
I am using xampp environment . Forget about the local setup. Why it was not
working in the demo url which I shared with you?

**Comment by DanielnetoDotCom** [comment]
I guess you will not be able to make it work on windows.

On demo I wrote above why was not working.

![image](https://user-images.githubusercontent.com/18009293/77424527-098b0980-6db0-11ea-9565-ffe38307024d.png)

**Comment by aliasgarvanak** [comment]
Hello,

Thank you for your response. I logged in to the website and started testing
live feature on demo server and It was not working.

**Comment by DanielnetoDotCom** [comment]
but is it working now?

**Comment by DanielnetoDotCom** [comment]
If you are not sure how to make a live stream, try this https://tutorials.avideo.com/video/9/youphptube-video-stream-with-obs-and-vmix?channelName=yeshua

**Comment by aliasgarvanak** [comment]
No same issue. Not working . But the link you sent was working. But it was
not working when I tried to go live

**Comment by DanielnetoDotCom** [comment]
So the problem is, you can not go live.

create a new use for you, then follow the video tutorial I paste above.

**Comment by aliasgarvanak** [comment]
Okay. Let me try that again with the tutorial

**Comment by GodgivenButhelezi** [comment]
Hai I recently bought the live users Plugin + other plugins only to find out that my Live Stream is not working and i believe to have installed it properly could you check and help please https://www.meetmycraft.com/Video-tunnel/

**Comment by DanielnetoDotCom** [comment]
@GodgivenButhelezi please check your Nginx log file

and also specify what error are you seeing.

**Comment by GodgivenButhelezi** [comment]
This is the error I'm Seing. "The media could not be loaded, either because the server or network failed or because the format is not supported."+

**Comment by GodgivenButhelezi** [comment]
This is what I see on my Nginx log file
-rw-r----- 1 nginx    adm     0 Jun 25  2019 access.log
drwxr-xr-x 2 root     root 4.0K Jun 25  2019 domains
-rw-r----- 1 www-data adm     0 Mar 17 06:25 error.log
-rw-r----- 1 www-data adm    81 Mar 16 15:23 error.log.1
-rw-r----- 1 www-data adm   216 Mar  4 10:27 error.log.2.gz
-rw-r----- 1 www-data adm    94 Mar  3 13:53 error.log.3.gz
-rw-r----- 1 www-data adm   210 Feb 29 07:24 error.log.4.gz
-rw-r----- 1 www-data adm   211 Feb 29 05:36 error.log.5.gz
-rw-r----- 1 www-data adm    97 Feb 19 21:50 error.log.6.gz
-rw-r----- 1 www-data adm    96 Jan 10 11:10 error.log.7.gz
-rw-r----- 1 www-data adm   238 Dec 15 09:20 error.log.8.gz
-rw-r----- 1 www-data adm   121 Jul 28  2019 error.log.9.gz

**Comment by DanielnetoDotCom** [comment]
You must verify the log file content

**Comment by GodgivenButhelezi** [comment]
How do I  Verify log file content ?please help

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#nginx-log-file

**Comment by GodgivenButhelezi** [comment]
When i use the command  tail -n 200 -f /usr/local/nginx/logs/error.log it says no such file. I installed Avideo platform using a Zip file and Extracted it into my FTP as well as the Encoder. Everything else seems to be working fine except the encoder and live streaming. When I Connect it says can't connect and show some message about rmtp not being installed.

**Comment by GodgivenButhelezi** [comment]
Thanks I Fixed it

**Comment by DanielnetoDotCom** [comment]
How did you fix it? please share.
