### ISSUE TITLE
Streaming from avideo

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3214]
It's not working on my android or Apple device. 
Is there anything one needs to set in addition to logging in?

**Comment by DanielnetoDotCom** [comment]
Did you try from OBS?

Is good if you try from PC first to make sure it is working and it is not a misconfiguration 

I reviewed your configuration and I notice a missing letter in the rtmp domain. It is fixed now and should work from the device

**Comment by fakeologist** [comment]
Getting error still 
![Screenshot_20200608-170345_AVideo](https://user-images.githubusercontent.com/66537018/84080870-ea614880-a9aa-11ea-9cf2-e87b94265bd6.jpg)

**Comment by DanielnetoDotCom** [comment]
Please make sure you close your app and open it again.
