### ISSUE TITLE
"Too many tries"?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3217]
Hi

We get many complains from users about when they are trying to verify their email it gives this error "Too many tries". And then they are not able to log in the site. I haven't been able to reproduce this. Log file says this: 

`User:_recommendChannelName too many tries `

I can turn off the email verification of course, but still.. Can you say is it maybe browser related or something?

T

**Comment by DanielnetoDotCom** [comment]
Can you please update your code?

I guess this is a bug that is already fixed.

**Comment by tonuzo** [comment]
Ok, did it. Thanks! 


T

**Comment by tonuzo** [comment]
This is not fixed. It gives the same error.... Can you please check this?

T

**Comment by tonuzo** [comment]
`[13-Jun-2020 04:14:43 UTC] AVideoLog::DEBUG: userCreate.json: session_id changed to neln6s*****t66sl
[13-Jun-2020 04:13:23 UTC] AVideoLog::DEBUG: getCaptchaImage: XJ2Up - session_name 84b11d********7aa62c4eda0 session_id: neln6s*****t66sl
[13-Jun-2020 04:13:23 UTC] AVideoLog::DEBUG: getCaptchaImage _SESSION[palavra] = (XJ2Up) - session_name 84b11d********7aa62c4eda0 session_id: neln6s*****t66sl

[13-Jun-2020 04:14:43 UTC] AVideoLog::DEBUG: captcha: session_id changed to neln6s*****t66sl
[13-Jun-2020 04:14:43 UTC] AVideoLog::DEBUG: Sending SMTP Email
[13-Jun-2020 04:13:23 UTC] AVideoLog::DEBUG: captcha: session_id changed to neln6s*****t66sl
[13-Jun-2020 04:14:44 UTC] AVideoLog::DEBUG: Sending SMTP Email
[13-Jun-2020 04:14:44 UTC] PHP Notice:  Undefined index: comment in /var/www/html/AVideo/objects/functions.php on line 458
[13-Jun-2020 04:14:45 UTC] AVideoLog::WARNING: Warning: The plugin [CustomizeUser::onUserSignup] takes 0.8729 seconds to complete.
[13-Jun-2020 04:14:45 UTC] AVideoLog::WARNING: /var/www/html/AVideo/objects/userCreate.json.php
[13-Jun-2020 04:14:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/AVideo/objects/functions.php on line 513
[13-Jun-2020 04:14:45 UTC] AVideoLog::DEBUG: sendSiteEmail [1] New user SignUp Automatic Response
[13-Jun-2020 04:14:45 UTC] AVideoLog::DEBUG: Sending SMTP Email
[13-Jun-2020 04:14:45 UTC] PHP Notice:  Undefined index: comment in /var/www/html/AVideo/objects/functions.php on line 458
[13-Jun-2020 04:14:46 UTC] AVideoLog::DEBUG: sendSiteEmail Success Info: New user SignUp Automatic Response "*******@gmail.com"
[13-Jun-2020 04:14:46 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/AVideo/objects/functions.php on line 513
[13-Jun-2020 04:14:46 UTC] AVideoLog::DEBUG: sendSiteEmail [1] SignUp Automatic Response
[13-Jun-2020 04:14:46 UTC] AVideoLog::DEBUG: Sending SMTP Email
[13-Jun-2020 04:14:46 UTC] PHP Notice:  Undefined index: comment in /var/www/html/AVideo/objects/functions.php on line 458
[13-Jun-2020 04:14:47 UTC] AVideoLog::DEBUG: sendSiteEmail Success Info: SignUp Automatic Response "*******@gmail.com"
[13-Jun-2020 04:14:47 UTC] AVideoLog::WARNING: Warning: The plugin [Notifications::onUserSignup] takes 1.708 seconds to complete.
[13-Jun-2020 04:14:47 UTC] AVideoLog::WARNING: /var/www/html/AVideo/objects/userCreate.json.php
[13-Jun-2020 04:14:52 UTC] AVideoLog::DEBUG: getCaptchaImage: znupm - session_name 84b11d********7aa62c4eda0 session_id: neln6s*****t66sl
[13-Jun-2020 04:14:52 UTC] AVideoLog::DEBUG: getCaptchaImage _SESSION[palavra] = (znupm) - session_name 84b11d********7aa62c4eda0 session_id: neln6s*****t66sl
[13-Jun-2020 04:15:28 UTC] AVideoLog::ERROR: User:_recommendChannelName too many tries
[13-Jun-2020 04:15:41 UTC] AVideoLog::ERROR: User:_recommendChannelName too many tries
[13-Jun-2020 04:16:20 UTC] AVideoLog::DEBUG: Start Login Request
[13-Jun-2020 04:16:20 UTC] AVideoLog::DEBUG: redirectUri: https://www.**********.***/signUp
[13-Jun-2020 04:16:20 UTC] AVideoLog::DEBUG: same redirectUri: https://www.**********.***/signUp
[13-Jun-2020 04:16:20 UTC] AVideoLog::DEBUG: user::login: noPass = , encodedPass = , this->user, *******@gmail.com 212.90.88.136
[13-Jun-2020 04:16:20 UTC] AVideoLog::DEBUG: encryptPasswordVerify: encrypt
[13-Jun-2020 04:16:20 UTC] AVideoLog::ERROR: User:_recommendChannelName too many tries
[13-Jun-2020 04:17:30 UTC] AVideoLog::ERROR: User:_recommendChannelName too many tries
[13-Jun-2020 04:17:37 UTC] AVideoLog::ERROR: User:_recommendChannelName too many tries`

**Comment by DanielnetoDotCom** [comment]
Please try this update now.
