### ISSUE TITLE
Upload to YouTube doesn't work

### ISSUE THREAD

**Issue by zauklian** [WWBN/AVideo#3228]
![youtube_upload](https://user-images.githubusercontent.com/538670/84375248-de2af480-ac11-11ea-8a15-28adacbf8829.png)

**Comment by DanielnetoDotCom** [comment]
It supposes to give you a link to click.
I am sending a fix for it.

**Comment by zauklian** [comment]
> 
> 
> It supposes to give you a link to click.
> I am sending a fix for it.

Now I can upload from local storage to youtube. But the video quality was low. Can I upload HD quality? 
Another one issue is when i upload from other storage (I used YPTStorage Plugin) i got the following error at youtube page. 
![youtube_upload_02](https://user-images.githubusercontent.com/538670/84495179-50b4d680-acdd-11ea-9a61-95343cb442be.png)

Thanks :)

**Comment by DanielnetoDotCom** [comment]
Hi

I see now.
I have never tested with the Storage, but this new update should do the trick and also use the highest resolution.
Also please **update your Avideo-Storage server and YPTStorage plugin**. yesterday I released some important updates. now the storage move runs in the background . and a lot of bug fixes.

**Comment by maxlinux2000** [comment]
HI I don't have YPTStorage plugin but the problem still here... this is a old bug that has come back to annoy  :-)

![Captura de pantalla de 2020-07-05 14-56-39](https://user-images.githubusercontent.com/5683921/86533284-68dcd780-bed0-11ea-86f4-0b6d87ba6f56.png)

(I have just updated my installation with git)

**Comment by akhilleusuggo** [comment]
You need YouTube API to be able to upload videos to Youtube

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/86533389-6e8aeb00-bed9-11ea-9437-118a96cfdce8.png)

**Comment by maxlinux2000** [comment]
Yes, I have do this... Goolge login enabled (and tested), Youtube APi3 enabled.... but still not working... and note that this war already actived on my site en version 8 of Avideo (youphptube)

**Comment by maxlinux2000** [comment]
I think that this error is related with this old bug https://github.com/WWBN/AVideo/issues/2596

**Comment by maxlinux2000** [comment]
Inspecting the youtubeUpload.json.php I can get this json file:

![Captura de pantalla de 2020-07-05 16-52-07](https://user-images.githubusercontent.com/5683921/86535393-4783e780-bee0-11ea-9ff5-56733e5de74e.png)

**Comment by DanielnetoDotCom** [comment]
If you update your site this bug should be gone already

**Comment by maxlinux2000** [comment]
> If you update your site this bug should be gone already

Hi,
 Sorry for delay... no, I just upgraded, but the bug still here.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot the error again?

**Comment by maxlinux2000** [comment]
![Captura de pantalla de 2020-07-29 20-32-19](https://user-images.githubusercontent.com/5683921/88928301-f665da00-d278-11ea-8ef0-2564ce0ce151.png)
Here yo have

**Comment by DanielnetoDotCom** [comment]
I just double check and the code is correct, can you please check what version are you running?

https://github.com/WWBN/AVideo/blob/e4cd2d9567bd04fb1f42ff0f4c7a55e3d0712ab3/view/managerVideos_body.php#L1622

**Comment by maxlinux2000** [comment]
Hi sorry for delaying

The error still present in the last build (AVideo 9.5) synced today.

But... This is only a error parsing the html code. If I copy/paste the url of message in another tab I can authorize Avideo and then upload the video to youtube.
When the upload finish another wrong parsed message appear

**Comment by DanielnetoDotCom** [comment]
I understand, but I cannot reproduce it here
