### ISSUE TITLE
Resolution switcher on HLS

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3831]
Hi

resolution switcher has these qualities by default. How can I change these on HLS? 

![image](https://user-images.githubusercontent.com/63721378/96131610-4efc5900-0ef1-11eb-86be-f0b60803e37a.png)

On HLS-plugin I have these parameters:

![image](https://user-images.githubusercontent.com/63721378/96131971-c03c0c00-0ef1-11eb-9d0c-e1bae4f2b6ea.png)

**Comment by jengajenga** [comment]
For HLS visit the Wiki and search for Adaptive Bitrate

**Comment by akhilleusuggo** [comment]
On plugin HLS , Edit parameters , 

![image](https://user-images.githubusercontent.com/52116577/96140448-9d692200-0f08-11eb-9a06-6922c977d296.png)

**Comment by akhilleusuggo** [comment]
Then it's bugged . It's the one option that should make the trick . @DanielnetoDotCom 

Try it on demo site .

**Comment by DanielnetoDotCom** [comment]
Please update your streamer and clear the cache. I guess now it is resolved.

**Comment by daoguey** [comment]
This is still not solved. #3848 is the same issue that I am having. even after clearing all it did was nothing.

**Comment by DanielnetoDotCom** [comment]
Is it also happening on demo site?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom How can we know , if demo site has no transcoding ?

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I do not get it.

are you talking about the HLS or Live?

for example, the livelink has a transcoding 

![image](https://user-images.githubusercontent.com/18009293/96780045-f5999b80-13c2-11eb-855e-beb87ef8f512.png)
