### ISSUE TITLE
v11.0 Direct Upload is producing videos that "can't find this video"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5111]
**Describe the bug**
Using direct upload for .mp4 files downloaded from Twitter is failing to produce a video that plays.

**To Reproduce**
1. Download a video file such as this 9.6MB commercial for the Central Intelligence Agency (attached for your testing)
2. Watch the video, and wonder why the CIA is capitulating to China (but I digress)
3. Using "Direct upload", upload that video
4. Observe that video does not have a poster frame in the videos list
5. Click on that video
6. Observe that it "cannot be found"

**Expected behavior**
Direct Upload not to have regressed

**Screenshots**
Curiously, Brave is reporting page not found from clicking on the videos link.

![Screen Shot 2021-05-09 at 3 55 56 PM](https://user-images.githubusercontent.com/11711050/117589568-27fcb300-b0df-11eb-865a-9b6e1c39ccfd.png)
![Screen Shot 2021-05-09 at 3 56 19 PM](https://user-images.githubusercontent.com/11711050/117589572-2a5f0d00-b0df-11eb-8410-b6a0f43d109d.png)

https://user-images.githubusercontent.com/11711050/117589518-d18f7480-b0de-11eb-828d-dc743d54cc1b.mp4

**Comment by DanielnetoDotCom** [comment]
you were right, this should fix the direct upload issue

**Comment by walt93** [comment]
What should fix the issue? Clue me in to your process, is there a branch I should pull and test, or is this rolled into next update, or ___?

**Comment by walt93** [comment]
I note that it did fix one thing, it picked up the poster frame in the Videos list, but the file is still not found when you go to its video page

**Comment by lunar54** [comment]
I applied fix and direct uploads work now but does not show correct file size 
![file_size](https://user-images.githubusercontent.com/35050024/117594714-517c0580-b104-11eb-8c90-d5ab96137a87.JPG)

**Comment by DanielnetoDotCom** [comment]
This should fix that

**Comment by millzee01** [comment]
I'm finding all my direct uploads are inactive by default and have to activate them before they can be played.

is there a setting that sets default direct uploads to Inactive?

**Comment by DanielnetoDotCom** [comment]
Check this 
![image](https://user-images.githubusercontent.com/18009293/117981268-362f1700-b30b-11eb-9fab-e84ac4a412cf.png)
