### ISSUE TITLE
VideoLogoOverlay Update, Player in Player and Logo position

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5180]
After the update, the profile picture of the video owner appears in the player.
If I deactivate this function, the Play logo appears at this point.
Before the update, my website logo was at the top on the right-hand side, after the update the website logo is displayed in the top left, although the plugin is entered in the top right.

Please remove the much too large user logo and the play image from the videos, cruel!

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, I found the issue and it is fixed now

**Comment by peterflitz** [comment]
Thanks Daniel.

But top right still not working in newest Version, in old Version all is fine.

**Comment by DanielnetoDotCom** [comment]
top right was tested here and it works. please make sure you clear the browser cache (NOT AVideo cache)

**Comment by peterflitz** [comment]
No settings possible to top right.
![Bildschirmfoto zu 2021-05-21 21-58-41](https://user-images.githubusercontent.com/76056428/119192315-37391480-ba80-11eb-85fd-ba2d2b8f3f03.png)

**Comment by DanielnetoDotCom** [comment]
Please try this

**Comment by peterflitz** [comment]
No selection is now possible in the dropdown field, not even a "textarea".

**Comment by DanielnetoDotCom** [comment]
On demo it is working

![image](https://user-images.githubusercontent.com/18009293/119208642-92b3d400-ba79-11eb-8f73-4d1624f4a9f4.png)

**Comment by peterflitz** [comment]
Since the update there are more problems, not all videos are running again ..., AD_Overlay is faulty ..., Meet no longer works.
Difficult ...

I always test on several different installs before posting.

It's also bad that I often find mistakes, but I seem to be the only one who notices.

Nobody uses
AD_Overlay, Meet, AdALiveLINK (as an example)?

**Comment by DanielnetoDotCom** [comment]
you must check your logs, I cannot see any problem here

**Comment by DanielnetoDotCom** [comment]
please update and try again

**Comment by peterflitz** [comment]
No change, the position of the logo cannot be changed.
With "Edit Logo" still no selection, an empty field ...

Cache etc. deleted, different browsers, the same everywhere.

**Comment by DanielnetoDotCom** [comment]
please try to change the position here 

![image](https://user-images.githubusercontent.com/18009293/119265730-17a80600-bbbe-11eb-8590-b8c76ce56193.png)


If it does not work, please reset the plugin deleting all the code, and save it

![image](https://user-images.githubusercontent.com/18009293/119265763-327a7a80-bbbe-11eb-9919-e4abed546bf0.png)

**Comment by peterflitz** [comment]
Hi Daniel,

yes, clearing the code helped.

But something is still wrong, the size of the logo cannot be changed and somehow nothing is copied with "Edit Logo".
Changes are only accepted in the parameters.

Can I specify the size of the logo in the code with the parameters?

**Comment by DanielnetoDotCom** [comment]
I just added the parameter `logoMaxWidthPX`, the default value is 150

**Comment by peterflitz** [comment]
Great, works fine.
Thanks Daniel :+1:

**Comment by guymass** [comment]
On my panel the menu for position selection doesn't open at all, I cannot set position, the logo is always at top left:

![Screen Shot 5781-09-21 at 11 21 51](https://user-images.githubusercontent.com/58882903/120291114-a2c68180-c2cb-11eb-81b0-306f282d251f.jpg)

**Comment by guymass** [comment]
OK we deleted the code and saved, then closed and re opened the plugin and it was reset we now could see and select the correct position.

**Comment by guymass** [comment]
URL for the logo doesn't work!
![Screen Shot 5781-09-21 at 11 42 10](https://user-images.githubusercontent.com/58882903/120295141-8b899300-c2cf-11eb-8790-43f74cc07cf0.jpg)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by morbificagent** [comment]
here its strange too. Changing settings under "edit parameters" or "edit Logo" arent reflected to each other. So if i change the Position to Top-Right under "edit parameters" and take a look under "edit Logo" the setting is "center" for example.
Confusing.

And the position of the Overlay is different from device to device.

For example i have selected "Top-Right" here. On my PC its looking ok (even if i would like to configure **some padding from the top**):
 
![image](https://user-images.githubusercontent.com/50199132/120458767-d969ce00-c397-11eb-930b-f1eea73e7e60.png)

But if i take a look on my smartphone the overlay jumps to strange positions:

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by morbificagent** [comment]
![Screenshot_20210602-190909_Firefox.jpg](https://user-images.githubusercontent.com/50199132/120524480-63855700-c3d7-11eb-8adf-ee7375a9d347.jpg)

The position looks good now but in my opinion its to big on mobile. No pc here to test at the moment...

Would it be possible to make a scaling value for us to change instead of making it hardcoded?

**Comment by DanielnetoDotCom** [comment]
You can add a custom CSS and overwrite those classes

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

https://github.com/WWBN/AVideo/blob/2c2638c1728c93c12841f1575a55ca5037033604/plugin/VideoLogoOverlay/style.css
