### ISSUE TITLE
Playback on Mobile/iOS does not engage full screen. Leaves much window dressing obscuring the player.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5513]
**Describe the bug**
Playback on iOS does not engage full screen. 

**To Reproduce**
1. Go to any iOS device
2. Play any video
3. Observe lack of full-screen capability

**Expected behavior**
To be able to play full screen. This is a major use case. iOS can stream to AppleTV, and gets a nice full screen user experience.

**Comment by DanielnetoDotCom** [comment]
Hi

if you are using the default player skin this update should resolve that

**Comment by walt93** [comment]
I did a git pull, updated my plug-ins while I was there, ran the 11.2 update script.
I switched my player skin to default.
I can see the player has changed, but, full screen still does not engage.
Please advise, thanks.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot so I can see what buttons you do have enabled?
