### ISSUE TITLE
AD_Server plug-in advertising payment blocking

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5553]
Is there any way to allow users to pay to block (AD_Server) plug-in ads

**Comment by DanielnetoDotCom** [comment]
On the plugins for-pay content. PPV, Subscription, etc you may find the parameter allowFreePlayWithAds

if this is checked the ads will be removed as soon as the user pays to watch

**Comment by chenjian9885** [comment]
allowFreePlayWithAds has been selected, but the ad can continue to play
![image](https://user-images.githubusercontent.com/47063171/129403173-19609f2e-be26-4fc3-b112-ebcd6e9bfefb.png)
![image](https://user-images.githubusercontent.com/47063171/129403204-f987df50-fcd6-4dd9-8d00-09a0e85a5442.png)
![image](https://user-images.githubusercontent.com/47063171/129403781-d33a5f5a-02a8-4ea2-8bf7-4843b567c293.png)
![image](https://user-images.githubusercontent.com/47063171/129403847-8ad26acb-6b70-4937-93fb-8c26e09efcfa.png)
![image](https://user-images.githubusercontent.com/47063171/129404103-f6418ec4-97b5-4165-9677-96a94bc3ac61.png)

Ads can still play

![image](https://user-images.githubusercontent.com/47063171/129405240-8f591afc-c623-4b36-bbaa-bf49d7359fe5.png)

**Comment by DanielnetoDotCom** [comment]
I guess only Google IMA plugin respect that rule.
you can use the VMAP/VAST link from the AD_Server plugin on the GoogleADs_IMA plugin

**Comment by chenjian9885** [comment]
Ads still can’t be eliminated
![image](https://user-images.githubusercontent.com/47063171/129520195-dfc3c4f3-51eb-49bf-ae63-2c732a618d9f.png)
![image](https://user-images.githubusercontent.com/47063171/129520251-5e64c0c0-5c58-46e9-aee7-dcea44df8ceb.png)
![image](https://user-images.githubusercontent.com/47063171/129520288-2bcd9d2a-7fa8-4255-9ae0-0414e8d3b64b.png)
![image](https://user-images.githubusercontent.com/47063171/129520365-588f2b85-7280-4194-892f-219f3cf1530a.png)
![image](https://user-images.githubusercontent.com/47063171/129520427-1aa4af1c-4569-4ff5-8516-f0e06f6f4a2b.png)
![image](https://user-images.githubusercontent.com/47063171/129520517-0fbe3041-fa9a-4fc3-86e3-ddcb1a798cfc.png)

**Comment by chenjian9885** [comment]
My paid plan
![image](https://user-images.githubusercontent.com/47063171/129520971-41e1a7f8-72b2-4e2e-84bb-41e2b289a423.png)
![image](https://user-images.githubusercontent.com/47063171/129521012-e809009f-25e2-4dd0-b84d-5f487c19e33e.png)
![image](https://user-images.githubusercontent.com/47063171/129521090-d7254e1a-0597-4967-8410-80de6b49f2e4.png)
![image](https://user-images.githubusercontent.com/47063171/129521187-55e050f5-58ca-43be-be4f-b0464b4549ed.png)

**Comment by DanielnetoDotCom** [comment]
when you tested that did you log off and log in again?

**Comment by chenjian9885** [comment]
Yes, I have logged out and logged in here

**Comment by DanielnetoDotCom** [comment]
Hi, I just check deeper into the code and I have reviewed this plugin.

I fixed some bugs and also I just made sure the AD_Server plugin respect the allowFreePlayWithAds option

please update it and try again

**Comment by chenjian9885** [comment]
Hello, I tested on (demo.avideo.com) and checked allowFreePlayWithAds on the PayPerView plug-in, but paid videos still have ads, on the contrary, free videos have no ads.
![image](https://user-images.githubusercontent.com/47063171/129677192-ef020854-0c63-4a56-992e-3860efe466e6.png)
![image](https://user-images.githubusercontent.com/47063171/129677241-da234784-f976-4a58-b993-dff000279960.png)

**Comment by chenjian9885** [comment]
Tested with AD_Server plug-in and GoogleAds_IMA plug-in and got the same results

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure what you have done, I just upload a new video and I made it a PPV video

https://demo.avideo.com/video/346/guy-penrod---because-he-lives-live-1
![image](https://user-images.githubusercontent.com/18009293/129742593-f02a6e9b-cfb7-4720-9f3c-8aec4b4ab7c5.png)


Also, I upload another video to use as an ad on AD_Server plugin

https://demo.avideo.com/video/347/short-video-ads-sample

![image](https://user-images.githubusercontent.com/18009293/129742781-b6775e78-21c0-4914-b27f-bc9bb1889704.png)


I created a plan for the Admin

![image](https://user-images.githubusercontent.com/18009293/129742494-1c6ab26d-8dc0-487a-8630-121e825376a9.png)

I used the user test pw test to login and purchased the PPV

![image](https://user-images.githubusercontent.com/18009293/129748602-0bd4a421-58fd-4cb2-a56d-1e4e55450c50.png)

All seems to be working fine.

this configuration will not reset anymore, I just saved this configuration so you can test it on the demo site

**Comment by chenjian9885** [comment]
Hello
I understand that ads can be cleared normally in paid video plans that have not ticked the user group. If the user group plan has been ticked, the ads cannot be cleared.
![image](https://user-images.githubusercontent.com/47063171/129781102-561eaad8-1342-458c-aad5-1d6800de6cb5.png)
![image](https://user-images.githubusercontent.com/47063171/129781103-223e7801-d71a-4948-a15c-485538a84a08.png)

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I am not sure what you mean and what was the difference

**Comment by chenjian9885** [comment]
This is my configuration
![image](https://user-images.githubusercontent.com/47063171/129959834-c9b05dc0-b4f6-48fd-8154-3ed490a320cd.png)
![image](https://user-images.githubusercontent.com/47063171/129959754-ed3cdf56-8bf4-4bfe-a7f0-9adf9e948274.png)
![image](https://user-images.githubusercontent.com/47063171/129960007-6530371e-cbc7-42d6-bc8c-7a1bed5880e9.png)
![image](https://user-images.githubusercontent.com/47063171/129960131-cbc68022-7f9f-4000-86b5-e0089dafd5ea.png)
![image](https://user-images.githubusercontent.com/47063171/129960301-cb94dde6-48cf-4b53-ae83-c6da8e19cb4e.png)
![image](https://user-images.githubusercontent.com/47063171/129960387-ad6e1d9b-09a0-4c3b-b879-73c032e6b8ef.png)
![image](https://user-images.githubusercontent.com/47063171/129960713-9c921b7c-b7f2-427e-9e10-feb5411e3e9a.png)
![image](https://user-images.githubusercontent.com/47063171/129960943-b660db05-f4e2-4d32-b380-fa221b512cdf.png)
![image](https://user-images.githubusercontent.com/47063171/129961204-358f3213-c463-46f4-ac68-dd66f2b5749a.png)
![image](https://user-images.githubusercontent.com/47063171/129961868-b83ea084-1433-49de-ab68-85770cf14051.png)

**Comment by chenjian9885** [comment]
Subscription plan created by User Groups, check allowFreePlayWithAds, it will not work

**Comment by DanielnetoDotCom** [comment]
Hi, the demo site is reset by now.

do you have this plugin installed on your site?
can I have access to it? (SSH and admin)

If you cannot I can share another test site for you then you will make the configuration that reproduces it and I will check it without resetting the site.

**Comment by chenjian9885** [comment]
Hello
Feel sorry! I haven't installed the PayPerView plug-in yet, I have added it to my shopping cart, and will wait for the test to pass before purchasing.

**Comment by chenjian9885** [comment]
So I can only test on the demo site, I can copy its configuration on your test site

**Comment by DanielnetoDotCom** [comment]
Hi, 

fell free to change the demo site , the demo site is reset multiple times a day

**Comment by chenjian9885** [comment]
Now let me reproduce it on the demo site (demo.avideo.com)?

**Comment by chenjian9885** [comment]
Please test on these two videos
Site: https://demo.avideo.com
![image](https://user-images.githubusercontent.com/47063171/130101193-ee04feed-a854-4ff5-81d9-4096eb5a1b78.png)

**Comment by chenjian9885** [comment]
My test user: test
Password: test

**Comment by DanielnetoDotCom** [comment]
I guess I found the problem, please try again.

this problem is fixed on PayPerView version 5.2

**Comment by chenjian9885** [comment]
awesome! It works well now.
