### ISSUE TITLE
NGINX Not working 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5720]
Something happened i was streaming and stopped and this is what is showing. What I can do?

![nginx](https://user-images.githubusercontent.com/63973045/133935858-3a1a445e-6676-41e5-a8aa-fdb59c3ae6a9.PNG)
![nginx2](https://user-images.githubusercontent.com/63973045/133935859-255eaa66-c073-48d1-829c-121ce388698a.PNG)

**Comment by DanielnetoDotCom** [comment]
what command are you using to start/stop the livestream?

**Comment by LATINMIXMASTERS** [comment]
i am n using any command i just check with this systemctl status nginx because when i tried to livestream is not connecting to server and i cannot live stream.

**Comment by DanielnetoDotCom** [comment]
that is why

the correct command is...

### Stop

`/usr/local/nginx/sbin/nginx - s stop`

### Start 

`/usr/local/nginx/sbin/nginx`

**Comment by LATINMIXMASTERS** [comment]
like i said i am not touching nginx i only trying to find why is not broadcasting and when i check is aying that

**Comment by milehighkaraoke** [comment]
Stat is working
![Screenshot_20210920-155246_Samsung Internet](https://user-images.githubusercontent.com/70327833/134080895-e3eb63fb-c71e-444f-9a65-6489fa4e6e05.jpg)

**Comment by DanielnetoDotCom** [comment]
I just read all your issue again, and sorry but I do not know what is the problem you are complaining about.

as I saw you used the wrong commands to check if nginx was running. and the error is expected (because the command is wrong)

I cannot see any problem on this issue

**Comment by DanielnetoDotCom** [comment]
Your Nginx is running

make sure you are also running the Sockets

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

![image](https://user-images.githubusercontent.com/18009293/134219515-32d9a8de-ccac-451c-87f5-d38bab54d42b.png)

**Comment by LATINMIXMASTERS** [comment]
I am still with issue of connecting to do stream what else i can do?


![socket](https://user-images.githubusercontent.com/63973045/134396033-75a9a55d-2be7-44f6-a22d-25d4976fb395.PNG)
![not connect](https://user-images.githubusercontent.com/63973045/134396046-6a922b04-f769-4b41-9803-3db89be965b7.PNG)

**Comment by DanielnetoDotCom** [comment]
Share your nginx.conf and also check your avideo log file

**Comment by LATINMIXMASTERS** [comment]
![nginx](https://user-images.githubusercontent.com/63973045/134820140-5b20e775-3e33-4a30-a795-7aafa55e61ee.PNG)

![nginx2](https://user-images.githubusercontent.com/63973045/134820145-2fec5041-a0bf-46e5-80dc-b1e26812e8dc.PNG)
![nginx 3](https://user-images.githubusercontent.com/63973045/134820149-d61a03c7-ac77-4b03-a221-936558f84e2e.PNG)
![nginx 4](https://user-images.githubusercontent.com/63973045/134820157-b5b80596-54f7-4e87-975b-92f67dd5f3b1.PNG)

**Comment by DanielnetoDotCom** [comment]
I cannot see anything wrong with your Nginx installation, 

I can only assume you are copying the wrong parameters

Please make sure you copy the parameters from **Device Stream Info**

![image](https://user-images.githubusercontent.com/18009293/134907416-765d9d6d-a50f-4d55-9c84-783ee1465773.png)

**Comment by LATINMIXMASTERS** [comment]
yes I am copying the correct stream key and stream url i dont know why keep saying 
![cannot](https://user-images.githubusercontent.com/63973045/134957123-d01748b2-3697-44a3-a7de-6b4f8c0db52b.PNG)

**Comment by DanielnetoDotCom** [comment]
1 hour ago I fixed your nginx.conf 

did you try again?

**Comment by LATINMIXMASTERS** [comment]
on  video.musicandstream.com still not working i reset key and all and still nothing.

**Comment by DanielnetoDotCom** [comment]
I see you are referring to another site ....

please share your live plugin parameters screenshot

**Comment by LATINMIXMASTERS** [comment]
![live](https://user-images.githubusercontent.com/63973045/134961780-f76777bf-477a-473f-b17c-9b5eb4652f85.PNG)

**Comment by DanielnetoDotCom** [comment]
I am not seeing any problem at all

if it is not working you should look again into your logs, right after a live stream attempt
