### ISSUE TITLE
Mobile app 403 embed is forbidden

### ISSUE THREAD

**Issue by ccarlile1** [WWBN/AVideo#6234]
When I try to play a video on the mobile app it displays 403 embed is forbidden. Is there a setting I have wrong?

**Comment by DanielnetoDotCom** [comment]
please make a git pull, it should be resolved

**Comment by ccarlile1** [comment]
I did a git pull and I still get the same thing. I did find however that if I make a series with a couple of videos that series will play. None of the other videos play that are not in a series will play. They still get the 403 embed is forbidden error.

**Comment by DanielnetoDotCom** [comment]
can you please check the avideo.log, should be something there regarding the forbid reason?

also can you please share a video link that is forbidden?

**Comment by ccarlile1** [comment]
I'm not seeing a log file in the AVideo directory. Would it be there or somewhere else?

The error is on the mobile app   diggertv.sugarsalem.org  any video gives the error.

**Comment by DanielnetoDotCom** [comment]
the file MUST be `AVideo/videos/avideo.log`

**Comment by DanielnetoDotCom** [comment]
Update again, and this update should give you more information why it is not allowed

**Comment by ccarlile1** [comment]
updated and the videos play now.

Thank you

**Comment by DanielnetoDotCom** [comment]
I found a bug on the update, I recommend you to make another git pull and try the video again

**Comment by ccarlile1** [comment]
OK, updated again and now it is not working again. But now says embed is forbidden admin

**Comment by DanielnetoDotCom** [comment]
The thing is, this should work with the mobile app, are you using our mobile app or a custom one?

but if you want to globally enable the embed you can uncheck this 

CustomizeAdvanced->blockEmbedFromSharedVideos

**Comment by DanielnetoDotCom** [comment]
the latest version?

what device? Android or iOS?

anyway. please uncheck CustomizeAdvanced->blockEmbedFromSharedVideos and you should be fine for now

**Comment by ccarlile1** [comment]
Yes latest version of android.
I unchecked the blockEmbed FromSharedVideos it is in the CustomizeUsers plugin. It is working now.
