### ISSUE TITLE
Block User doesnt hide their content

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6320]
I have a user telling me when he blocks a channel he still sees the videos on the homepage and new videos row on video playback.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot where exactly  is he seeing it?

**Comment by JoshWho** [comment]
![ttt](https://user-images.githubusercontent.com/39392449/156470174-30c883a0-2926-4ce3-adce-9237df4053c4.gif)

**Comment by JoshWho** [comment]
Did u get a chance to soe this @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
This should resolve this issue

**Comment by para2022** [comment]
This bug still exists I am getting the exact same bug now. I block a user and can still see their content then i block again and it says the user is already blocked. So it appears its not been fixed.

**Comment by DanielnetoDotCom** [comment]
what about after clearing the cache and reload the page a couple of times?

**Comment by para2022** [comment]
ah ha. I cleared my browser cache and all other caches. I went to block another user and after doing so i saw the red unblock button for a split second then as the videos on the right of the screen were loading at that point the unblock button changed back to block again and then when i click block again on the same user it says they are already blocked with no way to unblock them again and i can still see all their content. I suspect it has something to do with the new side loader cos at the very point that side bar refreshed is when the block button changed back from unblock to block again.

**Comment by para2022** [comment]
If i block them on their channel the same thing happens so its not the watch page side bar. When i press block i see the red unblock for a split second then it changes back and no way to unblock again.

**Comment by DanielnetoDotCom** [comment]
Strange, just checked on my side and it is working fine

**Comment by DanielnetoDotCom** [comment]
try to make a git pull

**Comment by para2022** [comment]
Thanks buddy i will look into it further my side. Must be a bug somewhere. Ive done i git pull i do them regular.

**Comment by para2022** [comment]
This bug still exists
