### ISSUE TITLE
calls

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6575]
Hey
I found this wonderful option for inter-channel calls

![photo_2022-05-11_09-49-30](https://user-images.githubusercontent.com/85537931/167786354-cca9ed11-4046-475a-be77-98a8f328eec5.jpg)

But it's only found in the Search Channels tab
Is there another place that this option appears?
For example it does not appear in the channel itself

![photo_2022-05-11_09-53-23](https://user-images.githubusercontent.com/85537931/167787150-f135b89b-76d6-47bb-84d3-af815ec5c9b8.jpg)

Thanks in advance
eitan live528

**Comment by DanielnetoDotCom** [comment]
It is supposed 

but the chat owner must be online 

also make sure you update your chat2 plugin

**Comment by eitanwa** [comment]
hey Daniel
I know but it still does not appear
Sending video
In addition, there is a bug that once the donations are activated in the channel, it appears in the chat twice
It also appears in the video I sent
Thank you and good day
eitan-live528

https://user-images.githubusercontent.com/85537931/167995496-548f66a9-0a67-48f5-8237-ca68ad62db9c.mp4

**Comment by DanielnetoDotCom** [comment]
Chat 10.2 should resolve the double donation buttons

**Comment by DanielnetoDotCom** [comment]
I guess I was missing something on the Chat 2 plugin, I just update the chat 2 version 10.3 and the caller seems to be working on it

**Comment by eitanwa** [comment]
Hey
Well I updated the chat
And still do not see the calls

When I check the chat page, it looks like the channels are not online
Although they are certainly online
  (At the same time, the channel page shows the sign that they are connected online)

Maybe this is the problem?

![image](https://user-images.githubusercontent.com/85537931/168459336-f09e98de-a3e3-401f-9b39-fa19064aa29b.png)

![image](https://user-images.githubusercontent.com/85537931/168459343-75d87d69-7197-4f53-a46f-9e9ce9082d2c.png)


![image](https://user-images.githubusercontent.com/85537931/168459346-1c587ab2-3381-4ba6-af9f-21f2d5b6842e.png)

**Comment by eitanwa** [comment]
I do not know if you have changed anything since I wrote the previous post
Either way I now see the indication of the conversations in the chat
![image](https://user-images.githubusercontent.com/85537931/168462511-58573a7b-dc29-4019-bbf6-a4a522847633.png)

I'll just add that the tab of the chat rooms
Inaccurate about the user's online

![image](https://user-images.githubusercontent.com/85537931/168462527-aaa794e4-13ff-4481-9624-12c57bc4ed16.png)

Thank you
 i Closes the post
