### ISSUE TITLE
Information not updated on video upgrade (Encoder)

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6740]
When a video is updated, in the encoder, the data inserted is not updated in the video that was replaced.

Regarding the time (duration) of the file, in this image you can see that the database keeps the information of the first file, and in the player the data of the new file is correct.

![image](https://user-images.githubusercontent.com/37880073/173929370-8d24c012-5435-46db-9c98-752919aee4d7.png)

I did a new test since the last encoder update and the problem still persists:
![image](https://user-images.githubusercontent.com/37880073/173931941-4758c27c-9849-448a-ab4d-e83f1e8ace82.png)

**Comment by DanielnetoDotCom** [comment]
Please update encoder and streamer. It should be fixed already

**Comment by gbrn** [comment]
I will run new tests

**Comment by gbrn** [comment]
I tried again and the problem persists...

File Original:
![image](https://user-images.githubusercontent.com/37880073/173973076-50301790-b7fc-441b-878f-60768c528ea3.png)

Adding video information in Encoder:
![image](https://user-images.githubusercontent.com/37880073/173973133-e90fe41c-221e-4a3b-a072-dbb6c631f71c.png)

And then the problem remains. Only the video is updated, all other information is not added (Title, Description). The duration of the new video is also not changed.
![image](https://user-images.githubusercontent.com/37880073/173989227-8f7a7166-2298-490f-a5ba-bdb1b3eb0c26.png)

**Comment by gbrn** [comment]
Several errors in the log, I don't know if it has relevance:

```
 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":1006,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":3138,"function":"getVideoFromFileNameLight","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":2273,"function":"getSourceFile","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":167,"function":"updateDurationIfNeed","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM  plugins WHERE status='active' AND uuid = 'CDN73225-3807-4167-ba81-0509dd280e06' ;) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/plugin.php","line":414,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":550,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":316,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":3096,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

...


 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":100,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":421,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM  plugins WHERE status='active' AND uuid = '26570956-dc62-46e3-ace9-86c6e8f9c81b' ;) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/plugin.php","line":414,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":550,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":316,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":83,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM categories ORDER BY id ASC LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":321,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":349,"function":"getCategoryDefault","class":"Category","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM categories WHERE id = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":265,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":102,"function":"getCategory","class":"Category","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":97,"function":"load","class":"Category","type":"->"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":347,"function":"__construct","class":"Category","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE clean_title = 'reaproveitar-7'  AND id != 212  LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":2737,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":314,"function":"fixCleanTitle","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2013) Lost connection to MySQL server during query (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:45:00 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":1006,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":4447,"function":"getVideoFromFileNameLight","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/functions.php","line":1974,"function":"clearCacheFromFilename","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":138,"function":"decideMoveUploadedToVideos"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

...
 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":1006,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":3138,"function":"getVideoFromFileNameLight","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":2273,"function":"getSourceFile","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":167,"function":"updateDurationIfNeed","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM  plugins WHERE status='active' AND uuid = 'CDN73225-3807-4167-ba81-0509dd280e06' ;) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/plugin.php","line":414,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":550,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":316,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":3096,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

...
 ************ ******** ****************** ***************** ****************** ******* ******* ****** ***** ****** *** **** **** ***************** * ******* ****** *** ***** * ************************** * ***************** ******** * *************************** ************* * *** ****** * **** *********** * *********************** ******** * ********** **** * ******** ******************* * *** ********* * *** ********* * *** ************** * ***** *********** * ** ******** * **  ******** * *** ******** * *** ******** * *** **** * **** ************ * **** ********* * **** ************* * **** ******* * *** *************** * ******************************************************************************* ******** * ***** ****************** * **** ***************************** * **** * ************** * ***  ********** * ******************************** ******** * ** * ******** * *** * ******************* * ***** * ******** * ****** **************** * ****  ***** ** * **** ******* * ** ************ ******************************* - password

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":100,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":421,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM  plugins WHERE status='active' AND uuid = '26570956-dc62-46e3-ace9-86c6e8f9c81b' ;) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/plugin.php","line":414,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":550,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/plugin\/AVideoPlugin.php","line":316,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":83,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM categories ORDER BY id ASC LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":321,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":349,"function":"getCategoryDefault","class":"Category","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM categories WHERE id = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":265,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":102,"function":"getCategory","class":"Category","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/category.php","line":97,"function":"load","class":"Category","type":"->"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":347,"function":"__construct","class":"Category","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE clean_title = 'reaproveitar-7'  AND id != 212  LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":2737,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":314,"function":"fixCleanTitle","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2013) Lost connection to MySQL server during query (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [16-Jun-2022 00:23:20 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/mysql_dal.php","line":231,"function":"log_error"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":1006,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/video.php","line":4447,"function":"getVideoFromFileNameLight","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/functions.php","line":1974,"function":"clearCacheFromFilename","class":"Video","type":"::"},{"file":"\/home\/storage\/e\/88\/c1\/guilhermeblanco\/public_html\/cnetv\/_beta30\/objects\/aVideoEncoder.json.php","line":138,"function":"decideMoveUploadedToVideos"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php
```

**Comment by DanielnetoDotCom** [comment]
With this problem 

```
MySQL server has gone away 
Lost connection to MySQL server during query
```

everything can happen.

I am not sure what type of server you have or what you are using, but this error does not happen here.

try this

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script

**Comment by gbrn** [comment]
@DanielnetoDotCom I took a new test. The image capture is ok, the image is updated correctly.

Do you think this error is related to server response time?


```
[18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: updateFilesize: No need to update videos_id=213 filename=video_220601112439_v3cb6 filesize=0 0 bytes SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php

[18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: getUsageFromFilename: is Dir dirSize=0 0 bytes path/to/my/streamer/site/videos/video_220601112439_v3cb6/ SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: getDirSize: ERROR ON Command du -sb path/to/my/streamer/site/videos/video_220601112439_v3cb6/ SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: getDirSize: start path/to/my/streamer/site/videos/video_220601112439_v3cb6/ SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php

[18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: deleteVideoTags getVideoTags213 SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: Video:clearCache(213) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: Video is done notified 213: REAPROVEITAR SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:01 America/Sao_Paulo] AVideoLog::DEBUG: updateFilesize: No need to update videos_id=213 filename=video_220601112439_v3cb6 filesize=0 0 bytes SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php

[18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: deleteVideoTags getVideoTags213 SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: Video:clearCache(213) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: Video::save (REAPROVEITAR) Saved id = 213  SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: deleteVideoTags getVideoTags213 SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: Video:clearCache(213) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php

[18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: deleteVideoTags getVideoTags213 SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:55:00 America/Sao_Paulo] AVideoLog::DEBUG: Video:clearCache(213) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
 [18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::DEBUG: aVideoEncoder.json: Success path/to/my/streamer/site/videos/video_220601112439_v3cb6/video_220601112439_v3cb6_HD.mp4  SCRIPT_NAME: /objects/aVideoEncoder.json.php
 [18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::DEBUG: aVideoEncoder.json: Files Received for video : REAPROVEITAR SCRIPT_NAME: /objects/aVideoEncoder.json.php
 [18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::DEBUG: Do not need update duration:  SCRIPT_NAME: /objects/aVideoEncoder.json.php
 [18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::DEBUG: Video::getSourceFile(video_220601112439_v3cb6, .mp4, 1) ERROR video not found (video_220601112439_v3cb6) SCRIPT_NAME: /objects/aVideoEncoder.json.php
```

[18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM  plugins WHERE status='active' AND uuid = '26570956-dc62-46e3-ace9-86c6e8f9c81b' ;) SCRIPT_NAME: /objects/aVideoEncoder.json.php

[18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2006) MySQL server has gone away (SELECT * FROM videos WHERE clean_title = 'reaproveitar-8'  AND id != 213  LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

[18-Jun-2022 17:54:59 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (2013) Lost connection to MySQL server during query (SELECT * FROM videos WHERE filename = ? LIMIT 1) SCRIPT_NAME: /objects/aVideoEncoder.json.php

**Comment by gbrn** [comment]
@DanielnetoDotCom I verify that the duration is now correct and the description is correct. Only the long and short title are not being updated.

![image](https://user-images.githubusercontent.com/37880073/174644425-05f523fb-67a7-4539-8076-785722169f62.png)

**Comment by DanielnetoDotCom** [comment]
If you mean when you swap videos. the titles and descriptions do not suppose to update. 

the idea is to keep the original information.

**Comment by DanielnetoDotCom** [comment]
when you swap a video all files will be replaced. 

video file and images, basically we change the whole folder, so all the uploaded images will be lost.

the original video metadata should remain (title, user groups, tags, etc).
