### ISSUE TITLE
Language Flag bug

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7831]
Hi,

Whenever i change the language flag on my site it defaults back to USA again. Happens on both sites. Its a recent bug.

Thanks

**Comment by gbrn** [comment]
This matter is being addressed in this issue #7822

**Comment by para2022** [comment]
Thank you. It seems the problem hasnt been resolved for that user either. I have the recent update and the problem still occurs. Thanks.

**Comment by DanielnetoDotCom** [comment]
can you please check the last git pull?

**Comment by para2022** [comment]
Still the same buddy after recent update. I change language move off page and then it resets back to USA every-time. Thanks

**Comment by DanielnetoDotCom** [comment]
sorry, I found another thing, please make a git pull again.

**Comment by para2022** [comment]
Fixed now. Thanks your help as usual Dan your a star!

**Comment by para2022** [comment]
Dan off topic. A while ago i reported a big where images randomly appear blurred. Ive solved it. If i delete all images in my videos dir with thumbsV2 in their filename every image on the site is fixed and none blurry. This happened on 3 servers so i knew it was the site. i have webp installed on my server. Any idea what caused this? as i said without those thumbs_V2 images everything is fixed now with probs on the site at all :P

**Comment by DanielnetoDotCom** [comment]
to be honest I have no idea

> Dan off topic. A while ago i reported a bug where images randomly appear blurred. And the only thing fixing them was to to edit thumbnail and save the thumb again. Ive solved it. If i delete all images in my videos dir with thumbsV2 in their filename every image on the site is fixed and none blurry. This happened on 3 servers so i knew it was the site. i have webp installed on my server. Any idea what caused this? as i said without those thumbs_V2 images everything is fixed now with probs on the site at all :P

**Comment by para2022** [comment]
Ok pal no worries pal i thought id quickly run it past you unless i was missing something. Im just glad i fixed it as its done my head in for months. Thank you

**Comment by para2022** [comment]
Is their anyway to stop it creating thumbsV2 images? they will not display and when it delete them they show properly again on the site.

**Comment by para2022** [comment]
Its still happening on a new build with mod_php

**Comment by para2022** [comment]
Ive fixed this by disabling webp completely webp causes hell on my site. Without it, just like before webp was implemented it works perfectly. No images errors whatsoever and no errors in logs.
