### ISSUE TITLE
404 error on embed

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7874]
Hi,

When i make embeds to social media im getting 404 error. The embed works but when i press play on it i get that blue page with the fancy 404 error message. I have no errors anywhere in my log. Any ideas? Many thanks

**Comment by DanielnetoDotCom** [comment]
please make a git pull, it was fixed a couple of days ago

**Comment by para2022** [comment]
Still doesn’t work and I did an update today already. All my sites embeds are broken everywhere unyet nothing was changed by me.

**Comment by DanielnetoDotCom** [comment]
can you share a link where your embed is broken?

**Comment by para2022** [comment]
Also you do have an images bug. Upload a video and it adds 2 images with thumbsv2 in the title and these cause issues. When I delete them the blurred image go away and it displayed correctly. If I save the same thumbnail again by going to the edit thumbnail option and just click save the blurred image is fixed and when I check the folder for that video the thumbsv2 images get deleted which is why saving the thumb again fixes the issue cos it removes the thumbsv2 images from the folder which in turn solves the blurred image issue so it is a problem clearly and it’s driven me mad for months. I never used to have image issues this time last year.

**Comment by para2022** [comment]
Here is a link that shares to gab social but get a 404 fancy page error when clicking play

https://ourtube.co.uk/v/44160

**Comment by para2022** [comment]
Hopefully these images will help. One is how it displays and the other is when i click play. All our embeds seem broken everywhere now, but when clicking the actually embed link in a browser it plays. very odd.

![Screenshot 2023-04-06 at 19 27 33](https://user-images.githubusercontent.com/107706817/230464701-713eb6f4-4eb2-479f-8641-6bc7acc8b934.png)

![Screenshot 2023-04-06 at 19 27 08](https://user-images.githubusercontent.com/107706817/230464769-c9b44953-ae87-45ec-8ba1-39c8cd943513.png)

**Comment by DanielnetoDotCom** [comment]
I just tested it locally and it works

did you change any files? did you change the .htaccess?

please double-check check you have it updated. 

it is something in your server...

this URL works

https://ourtube.co.uk/videoEmbed/44160/

but this one fails https://ourtube.co.uk/videoEmbed/44160/aaa


I cannot reproduce it on my servers check this for example https://tutorials.avideo.com/videoEmbed/10/streamer-and-encoder

or this, that is not a 404 error, it is a 403 (as I expect to be) https://tutorials.avideo.com/videoEmbed/44160/aaa

**Comment by para2022** [comment]
Thanks for the little tip their Dan with the second link /aaa that allowed me to resolve it. Its fixed now. Cheers bud :)
