### ISSUE TITLE
Broken videos again

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#8783]
3/24817 added to review https://ourtube.co.uk/v/24259 MEET Nina Jankowicz: Your new DHS DISINFORMATION CZAR - RESIST
3/24817 added to review https://ourtube.co.uk/v/22854 Corn Pop LOST HIS LAST MARBLE! Shakes hands with thin air!
3/24817 added to review https://ourtube.co.uk/v/20563 Pierre J - 1990 In The Mix
3/24817 added to review https://ourtube.co.uk/v/19610 Dr Ben Marble - People Have Been Vaccinated with Slow Acting Lethal Poison - Maria Zeee
3/24817 added to review https://ourtube.co.uk/v/18602 Dr Ben Marble | People Have Been Vaccinated with Slow Acting Lethal Poison
3/24817 added to review https://ourtube.co.uk/v/17415 Mahabharath: The Great Origin Of Everything
3/24817 added to review https://ourtube.co.uk/v/17322 Dr Leemon McHenry PhD | The Illusion of Evidence-Based Medicine
3/24817 added to review https://ourtube.co.uk/v/16011 Psaki - The NATIONAL GUARD has been activated in 48 states
3/24817 added to review https://ourtube.co.uk/v/15905 Nixon - Our work is what defines us
3/24817 added to review https://ourtube.co.uk/v/13710 Nice Truck Attack For DUMMIES!
3/24817 added to review https://ourtube.co.uk/v/10992 Her voice makes me want to vomit What person behaves in this manner?
3/24817 added to review https://ourtube.co.uk/v/9249 Carry on Henry VIII - 1971
3/24817 added to review https://ourtube.co.uk/v/6093 Hercules Child - Hércules niño
3/24817 added to review https://ourtube.co.uk/v/3822 The Very Best Of Euphoria Mixed By Matt Darey - CD1
3/24817 added to review https://ourtube.co.uk/v/2927 If I Were The Devil Would I Have Your Vote?
3/24817 added to review https://ourtube.co.uk/v/1814 Doctors speak out part 1
3/24817 added to review https://ourtube.co.uk/v/1811 Doctors Speak Out Part 2
3/24817 added to review https://ourtube.co.uk/v/1807 FALL OF THE CABAL - THE SEQUEL (Part 1)
3/24817 added to review https://ourtube.co.uk/v/376 ABSOLUTE PROOF THE COVID-19 SCAM WAS PLANNED LONG IN ADVANCE - MARK DEVLIN AT TRUTH JUICE PART 1
3/24817 added to review https://ourtube.co.uk/v/366 HAS BRITAIN FINALLY FOUND ITS BACKBONE
3/24817 added to review https://ourtube.co.uk/v/359 MELBOURNE WOMAN CHOKED OFF POLICE FOR NOT WEARING A MASK
3/24817 added to review https://ourtube.co.uk/v/270 SHOCK VIDEO: BILL GATES ADMITS COVID-19 VACCINE WILL KILL AND MAIM 700000
3/24817 added to review https://ourtube.co.uk/v/260 All These Different Events Taking Place Right Now
3/24817 added to review https://ourtube.co.uk/v/231 THE PLANNEDEMIC PART 1 DOCUMENTARY BY HIBBELER PRODUCTIONS
3/24817 added to review https://ourtube.co.uk/v/216 THE DOCTOR THAT DOESNT BELIEVE IN COVID-19
3/24817 added to review https://ourtube.co.uk/v/195 German Official Leaks Report Denouncing Corona as A Global False Alarm

I also found more not showing up here. These were all working for years as they all old videos. Removed about 50 new year also. Storage problem!

**Comment by para2022** [comment]
I cannot continue with this or il have no videos left on the site. They will not fix either like i fixed them all before which tells me they are totally broken. This keeps randomly occurring on my videos when i know for a fact these were all working. I have noticed none of them are encoded they are standard direct upload. And didnt we just have direct upload issues and videothumbnails bug at the exact time? I am totally convinced videothumbnails has broken most of my videos. I had no broken videos and i reinstalled that plugin yesterday and now i have loads of broken ones and I just cannot fix them no matter what i do. God only knows just how many are broken. My site is doomed now cos i sent an email out to users a few weeks back telling them all videos play now which they did.

**Comment by para2022** [comment]
Please fix your securevideosdirectoy plugin i have worked it out for you. God only knows what problems this has been creating on peoples websites. This is a site breaking bug that needs urgent attention. It is breaking peoples sites. It is turned off for now.

https://ourtube.co.uk/channel/MusicMonster/video/20563

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by lachainestoplinky** [comment]
ood morning,
I have the same problem, the videos I just sent end up with a status invisible to visitors and visible to the administrator.
the 15 videos sent this morning are visible to the last 3 this evening.
the encoder was modified because this morning, the remaining time was not visible and this evening yes.
should I do the latest update?
![Capture d’écran 2024-01-10 à 23 25 46](https://github.com/WWBN/AVideo/assets/39954233/58a3bbbe-ee8c-410e-89d9-879045dbb5d2)

I will look at the status in the database

**Comment by para2022** [comment]
> ood morning, I have the same problem, the videos I just sent end up with a status invisible to visitors and visible to the administrator. the 15 videos sent this morning are visible to the last 3 this evening. the encoder was modified because this morning, the remaining time was not visible and this evening yes. should I do the latest update? ![Capture d’écran 2024-01-10 à 23 25 46](https://private-user-images.githubusercontent.com/39954233/295734174-58a3bbbe-ee8c-410e-89d9-879045dbb5d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDA3MTMsIm5iZiI6MTcwNDk0MDQxMywicGF0aCI6Ii8zOTk1NDIzMy8yOTU3MzQxNzQtNThhM2JiYmUtZWU4Yy00MTBlLTg5ZDktODc5MDQ1ZGJiNWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAyMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZGMxOTgxYjIzNDcxMWNiOGMxMTY0ZDMzMGY4Yjc5ZDQwY2U4YTI1MGYwOWQ4NzZkZDYzYzEwNDhkNWFhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49XDkhMYdGx9jKvgki6OYmy8N7JD3B1bh3_zhfyBpcU)
> 
> I will look at the status in the database

You can release those videos by clicking on the tick in red

**Comment by lachainestoplinky** [comment]
Good morning,
That's it, I have this problem.
the problem comes from the encoder which does not give the visible status to visitors;
of my work, I sent videos, another person too.
it was not the same encoder because no time remaining.
I went to check the status of the 3 videos in the database.
it was in 'h' status and not 'a' like the others.
I changed it and they became visible to visitors

**Comment by lachainestoplinky** [comment]
Hello, I updated to Video 14.2
thank you for your message. the videos are therefore visible to visitors.
I had 4 pages of broken videos (40) I fixed everything.
only videos from 2021 and 2022.
Sincerely
Jerome

**Comment by DanielnetoDotCom** [comment]
Check for plugins updates 

If after update all still an issue share a link for a broken video

**Comment by lachainestoplinky** [comment]
ello, 
I think I returned the videos folder to the site. 
there was a cut. 
the videos folder is up to date and I also did the latest so-called update.
with your latest fixes
Sincerely
