### ISSUE TITLE
[Plugin SubtitleSwitcher] Error Create Subtitle

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9183]
@DanielnetoDotCom Danny, Create Subtitle (Plugin SubtitleSwitcher) isn't working... when I click the button, it doesn't open anything, in any video.
https://github.com/WWBN/AVideo/assets/37880073/1b802df9-a6cf-4dfa-96f4-e66a04897018

**Comment by DanielnetoDotCom** [comment]
Please check SubtitleSwitcher version 6.9, it should be fixed

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#addressing-permission-issues

**Comment by GreenDragonTavern** [comment]
I guess you missed the "Tried manually and still a no go." part of comment.

**Comment by DanielnetoDotCom** [comment]
did you delete the SubtitleSwitcher folder before upload it again?

**Comment by GreenDragonTavern** [comment]
Yes, removed entire folder then used AVideo plugins. That failed...in that AVideo still shows **Update Available: v6.9**. Then tried removing folder, deleting record from plugins table and then using AVideo plugins, again same result. Something is amiss because after updating plugin, the version on disk is 6.9, record in plugins table shows 6.8 even after deleting the record and letting AVideo recreate it using plugin upload.

**Comment by DanielnetoDotCom** [comment]
Sorry, I can see now I missed a information in the plugin

your plugin is updated already, it is detecting the old version

you do not have to but if you want you can download it again from marketplace and this new download will show you the v6.9 properly

**Comment by GreenDragonTavern** [comment]
Downloaded again from marketplace and yep, updates accordingly. Thank you.
