### ISSUE TITLE
 Videos for kids

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9783]
Hi Daniel,

 is there an option for the videos that are set for children not to appear in the normal interface (not children)?

Regarding the button, its visibility is normal, is that how it should look?
![image](https://github.com/user-attachments/assets/a7dc4c5a-be5a-4dd5-8267-6290c68074ba)

when is on looks normal
![image](https://github.com/user-attachments/assets/2aeeb9e9-cfaf-435d-9520-9d65bc4859e8)

At first I thought it was for security now not sure
TNKS

**Comment by eitanwa** [comment]
Basically 2 questions
One is whether it is possible to determine  that the videos I chose to display in the interface "for children" will only be displayed there
 And not in the normal interface?
(In the interface for children, you only see the videos you set
But they are still displayed in the normal interface as well)

Second question: the visibility of the button for children
Is this how it should look?

**Comment by eitanwa** [comment]
Okay, I understand why you didn't understand
It only happens when you change the language

**Comment by guymass** [comment]
On the Hebrew language that button appears offside, probably a CSS issue.

![Screenshot 5785-04-07 at 17 37 56](https://github.com/user-attachments/assets/87285ff3-5449-4e7a-81f8-d7b62a29d9ce)

**Comment by DanielnetoDotCom** [comment]
I see, so the issue is the design? that is broken on LTR languages?

**Comment by eitanwa** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by eitanwa** [comment]
> Please check this update

That fixed the button
Thanks Daniel

**Comment by eitanwa** [comment]
Now I see it has reversed the buttons on the plugins screen
Change to RTL language and you will see it in the plugins screen

![image](https://github.com/user-attachments/assets/2a29e991-26f9-4ce8-a992-9f22e506c59f)

**Comment by DanielnetoDotCom** [comment]
please check this

**Comment by eitanwa** [comment]
Many things have changed related to language now
There are areas related to language that I didn't even think it could be different
It will take me a while to go through everything
I will update you
Thanks Daniel

**Comment by guymass** [comment]
Hi Daniel, I still for some reason have problem translating strings to Hebrew. Here are some of the string in screenshots.
![Screenshot 5785-04-10 at 12 34 02](https://github.com/user-attachments/assets/5d3416a0-019e-49e3-b3c3-2c7918544021)
![Screenshot 5785-04-10 at 12 33 47](https://github.com/user-attachments/assets/6c4ff18b-dda1-4fa5-ae78-8a27a9673b39)
![Screenshot 5785-04-10 at 12 33 32](https://github.com/user-attachments/assets/c56fa9e3-bfaa-4352-bb20-7c6aec1299c4)

What can I do to force the translation? or how can I check the log to locate translation issues?

**Comment by eitanwa** [comment]
Hi Daniel

Here when we change to our language
it responds differently
In Hebrew the subtitles and resolution indication cannot be seen

english

![Image](https://github.com/user-attachments/assets/c485d844-af5a-4d56-8695-4256d36f8102)

hebrew
![Image](https://github.com/user-attachments/assets/56d285b6-9530-45cb-8998-b0f665ab60d4)

You can go to this link and simply switch between languages.
https://alive528.com/video/24603

----------------------------------------------------

This is a screenshot from my video screen
That's how it is in English

![Image](https://github.com/user-attachments/assets/77195955-6611-42c3-8b24-874e58752ed4)

in hebrew Should be the same

![Image](https://github.com/user-attachments/assets/27c4b0d7-d9e3-4248-973f-f7399697bc69)

**Comment by guymass** [comment]
This is fixed @eitanwa you can close this post.

**Comment by eitanwa** [comment]
this one still not
![Image](https://github.com/user-attachments/assets/cb5b2397-adf3-4bbb-bb2f-a38f8abae780)
@guymass

**Comment by DanielnetoDotCom** [comment]
Pleae check this

**Comment by eitanwa** [comment]
> Pleae check this


Thanks Daniel, this update fixed the plugins screen

I'm closing this post
Although I wrote in this post a few more issues that were not fixed
It got messy with a few things, some of which were fixed

I'll make it more organized and clear in new posts
